# Generated by Django 4.1.7 on 2023-03-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books_following',
        ),
        migrations.AddField(
            model_name='student',
            name='following_books',
            field=models.ManyToManyField(related_name='following_students', through='students.Following', to='books.book'),
        ),
    ]
